In [2]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
from tqdm import tqdm
import requests
import json
from datetime import datetime 
import time
import random
import wrangle as w

import warnings
warnings.filterwarnings('ignore')

In [3]:
season_2024 = w.nfl_data_scrape()
season_2024

Enter the first year of the season you want to collect data from:  2024
Enter the last year of the season you want to collect data from:  2024
Enter a filename for this data to save as a csv file (no need to add extenison of file):  nfl_data_2024_season

Number Of Seasons = 1
Number Of Teams = 32

Processing NFL Seasons: 100%|███████████████| 32/32 [04:30<00:00,  8.47s/Season]

Data will be saved as: nfl_data_2024_season.csv

,season,team,Week,Day,Date,Unnamed: 3,Unnamed: 4,OT,Unnamed: 6,Opp,...,FGA,XPM,XPA,Pnt,Yds.3,3DConv,3DAtt,4DConv,4DAtt,ToP
0,2024,CRD,1,Sun,September 8,boxscore,L,NaN,@,Buffalo Bills,...,2,4,4,2,85,3,9,2,2,30:30
1,2024,CRD,2,Sun,September 15,boxscore,W,NaN,NaN,Los Angeles Rams,...,1,1,1,4,215,2,11,1,3,23:06
2,2024,CRD,3,Sun,September 22,boxscore,L,NaN,NaN,Detroit Lions,...,0,2,3,5,247,6,12,0,1,36:49
3,2024,CRD,4,Sun,September 29,boxscore,L,NaN,NaN,Washington Commanders,...,2,4,4,1,51,9,12,1,1,33:22
4,2024,CRD,5,Sun,October 6,boxscore,W,NaN,@,San Francisco 49ers,...,3,2,2,1,41,6,11,0,1,32:58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539,2024,WAS,13,Sun,December 1,boxscore,W,NaN,NaN,Tennessee Titans,...,2,1,1,4,213,5,12,0,1,19:47
540,2024,WAS,15,Sun,December 15,boxscore,W,NaN,@,New Orleans Saints,...,2,1,1,4,187,3,11,1,1,19:10
541,2024,WAS,16,Sun,December 22,boxscore,W,NaN,NaN,Philadelphia Eagles,...,5,3,3,4,160,3,16,3,3,36:18
542,2024,WAS,17,Sun,December 29,boxscore,W,OT,NaN,Atlanta Falcons,...,2,3,3,3,141,2,10,2,2,25:46
543,2024,WAS,18,Sun,January 5,boxscore,W,NaN,@,Dallas Cowboys,...,4,1,1,4,198,7,17,1,2,37:03

In [6]:
season_2024 = w.clean_data('nfl_data_2024_season.csv')
season_2024 = w.final_cleaned_df(season_2024)
season_2024

,game_id,home_team,away_team,date,season,month,week,day_of_week,overtime,home_pts,...,away_4datt,home_top,away_top,pts_diff_home,pass_yds_diff_home,rush_yds_diff_home,top_diff_home,home_total_yds,away_total_yds,home_results
0,2024_1_Kansas City Chiefs_Baltimore Ravens,Kansas City Chiefs,Baltimore Ravens,2024-09-05,2024,9,1,3,0,27,...,2,1577,2023,7,14,-113,-446,353,452,1
1,2024_1_Philadelphia Eagles_Green Bay Packers,Philadelphia Eagles,Green Bay Packers,2024-09-06,2024,9,1,4,0,34,...,1,1967,1633,5,15,-19,334,410,414,1
2,2024_1_New Orleans Saints_Carolina Panthers,New Orleans Saints,Carolina Panthers,2024-09-08,2024,9,1,6,0,47,...,3,2199,1401,37,64,122,798,379,193,1
3,2024_1_Chicago Bears_Tennessee Titans,Chicago Bears,Tennessee Titans,2024-09-08,2024,9,1,6,0,24,...,2,1506,2094,7,-40,-56,-588,148,244,1
4,2024_1_Cincinnati Bengals_New England Patriots,Cincinnati Bengals,New England Patriots,2024-09-08,2024,9,1,6,0,10,...,0,1557,2043,-6,34,-100,-486,224,290,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,2024_18_New York Jets_Miami Dolphins,New York Jets,Miami Dolphins,2025-01-05,2024,1,18,4,0,32,...,3,1676,1924,12,58,-17,-248,375,334,1
268,2024_18_Tennessee Titans_Houston Texans,Tennessee Titans,Houston Texans,2025-01-05,2024,1,18,4,0,14,...,2,1799,1801,-9,62,-122,-2,314,374,0
269,2024_18_Arizona Cardinals_San Francisco 49ers,Arizona Cardinals,San Francisco 49ers,2025-01-05,2024,1,18,4,0,47,...,2,1689,1911,23,-56,13,-222,393,436,1
270,2024_18_Philadelphia Eagles_New York Giants,Philadelphia Eagles,New York Giants,2025-01-05,2024,1,18,4,0,20,...,4,1788,1812,7,114,-49,-24,303,238,1
271,2024_18_Denver Broncos_Kansas City Chiefs,Denver Broncos,Kansas City Chiefs,2025-01-05,2024,1,18,4,0,38,...,2,2509,1091,38,250,131,1418,479,98,1

In [9]:
season_2024.to_csv('nfl_data_2024_season.csv', index = False)

In [5]:
old_data = pd.read_csv('getting_there.csv')

In [8]:
old_data.head(3)

,game_id,home_team,away_team,date,season,month,week,day_of_week,overtime,home_pts,...,away_4datt,home_top,away_top,pts_diff_home,pass_yds_diff_home,rush_yds_diff_home,top_diff_home,home_total_yds,away_total_yds,home_results
0,2000_1_New York Giants_Arizona Cardinals,New York Giants,Arizona Cardinals,2000-09-03,2000,9,1,6,0,21,...,2,1890,1710,5,-140,180,180,395,355,1
1,2000_1_New England Patriots_Tampa Bay Buccaneers,New England Patriots,Tampa Bay Buccaneers,2000-09-03,2000,9,1,6,0,16,...,0,1705,1895,-5,34,-52,-190,278,296,0
2,2000_1_Pittsburgh Steelers_Baltimore Ravens,Pittsburgh Steelers,Baltimore Ravens,2000-09-03,2000,9,1,6,0,0,...,1,1493,2107,-16,-3,-110,-614,223,336,0

In [6]:
old_data.shape

(6175, 70)

In [7]:
#df should have 544 rows/games and 70 columns

544

In [13]:
season_2024.to_csv('nfl_data_2024_season', index= False)

In [16]:
clean_data = w.clean_data('nfl_data_2024_season')
clean_data.head(3)

,season,team,week,day,date,result,ot,host,opp,pts,...,fga_opp,xpm_opp,xpa_opp,pnt_opp,punt_yds_opp,3dconv_opp,3datt_opp,4dconv_opp,4datt_opp,top_opp
0,2024,CRD,1,Sun,September 8,L,no,away,Buffalo Bills,28.0,...,2.0,4.0,4.0,2.0,85.0,3.0,9.0,2.0,2.0,30:30
1,2024,CRD,2,Sun,September 15,W,no,home,Los Angeles Rams,41.0,...,1.0,1.0,1.0,4.0,215.0,2.0,11.0,1.0,3.0,23:06
2,2024,CRD,3,Sun,September 22,L,no,home,Detroit Lions,13.0,...,0.0,2.0,3.0,5.0,247.0,6.0,12.0,0.0,1.0,36:49

In [20]:
shared_columns = list(set(old_data.columns) & set(clean_data.columns))
not_shared = list(set(old_data.columns) - set(clean_data.columns))

shared_columns

['date', 'season', 'week']

In [ ]:
team_code_map = {
    'CRD': 'Arizona Cardinals',
    'ATL': 'Atlanta Falcons',
    'RAV': 'Baltimore Ravens',
    'BUF': 'Buffalo Bills',
    'CAR': 'Carolina Panthers',
    'CHI': 'Chicago Bears',
    'CIN': 'Cincinnati Bengals',
    'CLE': 'Cleveland Browns',
    'DAL': 'Dallas Cowboys',
    'DEN': 'Denver Broncos',
    'DET': 'Detroit Lions',
    'GNB': 'Green Bay Packers',
    'CLT': 'Indianapolis Colts',
    'JAX': 'Jacksonville Jaguars',
    'KAN': 'Kansas City Chiefs',
    'SDG': 'Los Angeles Chargers',
    'RAM': 'Los Angeles Rams',
    'RAI': 'Las Vegas Raiders',
    'MIA': 'Miami Dolphins',
    'MIN': 'Minnesota Vikings',
    'NWE': 'New England Patriots',
    'NOR': 'New Orleans Saints',
    'NYG': 'New York Giants',
    'NYJ': 'New York Jets',
    'PHI': 'Philadelphia Eagles',
    'PIT': 'Pittsburgh Steelers',
    'SEA': 'Seattle Seahawks',
    'SFO': 'San Francisco 49ers',
    'TAM': 'Tampa Bay Buccaneers',
    'OTI': 'Tennessee Titans',
    'WAS': 'Washington Commanders',
    'HTX': 'Houston Texans'
}

# Step 1: Replace team abbreviations in the 'team' column with full names
clean_data['team_full_name'] = clean_data['team'].map(team_code_map)

In [24]:
clean_data

,season,team,week,day,date,result,ot,host,opp,pts,...,xpm_opp,xpa_opp,pnt_opp,punt_yds_opp,3dconv_opp,3datt_opp,4dconv_opp,4datt_opp,top_opp,team_full_name
0,2024,CRD,1,Sun,September 8,L,no,away,Buffalo Bills,28.0,...,4.0,4.0,2.0,85.0,3.0,9.0,2.0,2.0,30:30,Arizona Cardinals
1,2024,CRD,2,Sun,September 15,W,no,home,Los Angeles Rams,41.0,...,1.0,1.0,4.0,215.0,2.0,11.0,1.0,3.0,23:06,Arizona Cardinals
2,2024,CRD,3,Sun,September 22,L,no,home,Detroit Lions,13.0,...,2.0,3.0,5.0,247.0,6.0,12.0,0.0,1.0,36:49,Arizona Cardinals
3,2024,CRD,4,Sun,September 29,L,no,home,Washington Commanders,14.0,...,4.0,4.0,1.0,51.0,9.0,12.0,1.0,1.0,33:22,Arizona Cardinals
4,2024,CRD,5,Sun,October 6,W,no,away,San Francisco 49ers,24.0,...,2.0,2.0,1.0,41.0,6.0,11.0,0.0,1.0,32:58,Arizona Cardinals
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539,2024,WAS,13,Sun,December 1,W,no,home,Tennessee Titans,42.0,...,1.0,1.0,4.0,213.0,5.0,12.0,0.0,1.0,19:47,Washington Commanders
540,2024,WAS,15,Sun,December 15,NaN,no,away,New Orleans Saints,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Washington Commanders
541,2024,WAS,16,Sun,December 22,NaN,no,home,Philadelphia Eagles,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Washington Commanders
542,2024,WAS,17,Sun,December 29,NaN,no,home,Atlanta Falcons,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Washington Commanders
543,2024,WAS,18,Sun,January 5,NaN,no,away,Dallas Cowboys,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Washington Commanders

In [26]:
#Create a unique identifier for each game
# This ensures each game is represented only once, even if it's recorded from both teams' perspectives
clean_data['game_id'] = clean_data.apply(lambda row: f"{row['season']}_{row['week']}_{'_'.join(sorted([row['team_full_name'], row['opp']]))}", axis=1)

In [27]:
clean_data

,season,team,week,day,date,result,ot,host,opp,pts,...,xpa_opp,pnt_opp,punt_yds_opp,3dconv_opp,3datt_opp,4dconv_opp,4datt_opp,top_opp,team_full_name,game_id
0,2024,CRD,1,Sun,September 8,L,no,away,Buffalo Bills,28.0,...,4.0,2.0,85.0,3.0,9.0,2.0,2.0,30:30,Arizona Cardinals,2024_1_Arizona Cardinals_Buffalo Bills
1,2024,CRD,2,Sun,September 15,W,no,home,Los Angeles Rams,41.0,...,1.0,4.0,215.0,2.0,11.0,1.0,3.0,23:06,Arizona Cardinals,2024_2_Arizona Cardinals_Los Angeles Rams
2,2024,CRD,3,Sun,September 22,L,no,home,Detroit Lions,13.0,...,3.0,5.0,247.0,6.0,12.0,0.0,1.0,36:49,Arizona Cardinals,2024_3_Arizona Cardinals_Detroit Lions
3,2024,CRD,4,Sun,September 29,L,no,home,Washington Commanders,14.0,...,4.0,1.0,51.0,9.0,12.0,1.0,1.0,33:22,Arizona Cardinals,2024_4_Arizona Cardinals_Washington Commanders
4,2024,CRD,5,Sun,October 6,W,no,away,San Francisco 49ers,24.0,...,2.0,1.0,41.0,6.0,11.0,0.0,1.0,32:58,Arizona Cardinals,2024_5_Arizona Cardinals_San Francisco 49ers
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539,2024,WAS,13,Sun,December 1,W,no,home,Tennessee Titans,42.0,...,1.0,4.0,213.0,5.0,12.0,0.0,1.0,19:47,Washington Commanders,2024_13_Tennessee Titans_Washington Commanders
540,2024,WAS,15,Sun,December 15,NaN,no,away,New Orleans Saints,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Washington Commanders,2024_15_New Orleans Saints_Washington Commanders
541,2024,WAS,16,Sun,December 22,NaN,no,home,Philadelphia Eagles,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Washington Commanders,2024_16_Philadelphia Eagles_Washington Commanders
542,2024,WAS,17,Sun,December 29,NaN,no,home,Atlanta Falcons,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Washington Commanders,2024_17_Atlanta Falcons_Washington Commanders
543,2024,WAS,18,Sun,January 5,NaN,no,away,Dallas Cowboys,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Washington Commanders,2024_18_Dallas Cowboys_Washington Commanders

In [28]:
# Step 2: Drop duplicate entries based on the game_id
# Keep only one entry for each game (e.g., keeping the first occurrence)
df_cleaned = clean_data.drop_duplicates(subset='game_id', ignore_index= True)


# Step 3: Drop the 'game_id' column if it's no longer needed
#df_cleaned = df_cleaned.drop(columns=['game_id'])

In [46]:
df_cleaned.reset_index(drop='index', inplace= True)

In [47]:
# Made home and away columns 
df_cleaned['home_team'] = df_cleaned.apply(lambda row: row['team_full_name'] if row['host'] == 'home' else row['opp'], axis = 1)
df_cleaned['away_team'] = df_cleaned.apply(lambda row: row['opp'] if row['host'] == 'home' else row['team_full_name'], axis = 1)
df_cleaned.head()

,season,team,week,day,date,result,ot,host,opp,pts,...,punt_yds_opp,3dconv_opp,3datt_opp,4dconv_opp,4datt_opp,top_opp,team_full_name,game_id,home_team,away_team
0,2024,CRD,1,Sun,September 8,L,no,away,Buffalo Bills,28.0,...,85.0,3.0,9.0,2.0,2.0,30:30,Arizona Cardinals,2024_1_Arizona Cardinals_Buffalo Bills,Buffalo Bills,Arizona Cardinals
1,2024,CRD,2,Sun,September 15,W,no,home,Los Angeles Rams,41.0,...,215.0,2.0,11.0,1.0,3.0,23:06,Arizona Cardinals,2024_2_Arizona Cardinals_Los Angeles Rams,Arizona Cardinals,Los Angeles Rams
2,2024,CRD,3,Sun,September 22,L,no,home,Detroit Lions,13.0,...,247.0,6.0,12.0,0.0,1.0,36:49,Arizona Cardinals,2024_3_Arizona Cardinals_Detroit Lions,Arizona Cardinals,Detroit Lions
3,2024,CRD,4,Sun,September 29,L,no,home,Washington Commanders,14.0,...,51.0,9.0,12.0,1.0,1.0,33:22,Arizona Cardinals,2024_4_Arizona Cardinals_Washington Commanders,Arizona Cardinals,Washington Commanders
4,2024,CRD,5,Sun,October 6,W,no,away,San Francisco 49ers,24.0,...,41.0,6.0,11.0,0.0,1.0,32:58,Arizona Cardinals,2024_5_Arizona Cardinals_San Francisco 49ers,San Francisco 49ers,Arizona Cardinals

In [83]:
df = df_cleaned

In [99]:
# Function to convert "minutes:seconds" to total seconds
def convert_to_seconds(time_str):
    minutes, seconds = map(int, time_str.split(':'))
    return minutes * 60 + seconds

# Apply the function to the 'top' column
df['total_top'] = df['top'].apply(convert_to_seconds)
df['opp_total_top'] = df['top_opp'].apply(convert_to_seconds)
df.head()

,season,team,week,day,date,result,ot,host,opp,pts,...,3datt_opp,4dconv_opp,4datt_opp,top_opp,team_full_name,game_id,home_team,away_team,total_top,opp_total_top
0,2024,CRD,1,Sun,September 8,L,no,away,Buffalo Bills,28.0,...,9.0,2.0,2.0,30:30,Arizona Cardinals,2024_1_Arizona Cardinals_Buffalo Bills,Buffalo Bills,Arizona Cardinals,1770,1830
1,2024,CRD,2,Sun,September 15,W,no,home,Los Angeles Rams,41.0,...,11.0,1.0,3.0,23:06,Arizona Cardinals,2024_2_Arizona Cardinals_Los Angeles Rams,Arizona Cardinals,Los Angeles Rams,2214,1386
2,2024,CRD,3,Sun,September 22,L,no,home,Detroit Lions,13.0,...,12.0,0.0,1.0,36:49,Arizona Cardinals,2024_3_Arizona Cardinals_Detroit Lions,Arizona Cardinals,Detroit Lions,1391,2209
3,2024,CRD,4,Sun,September 29,L,no,home,Washington Commanders,14.0,...,12.0,1.0,1.0,33:22,Arizona Cardinals,2024_4_Arizona Cardinals_Washington Commanders,Arizona Cardinals,Washington Commanders,1598,2002
4,2024,CRD,5,Sun,October 6,W,no,away,San Francisco 49ers,24.0,...,11.0,0.0,1.0,32:58,Arizona Cardinals,2024_5_Arizona Cardinals_San Francisco 49ers,San Francisco 49ers,Arizona Cardinals,1622,1978

In [77]:
# add this step to function 
df.fillna('0', inplace=True)

In [97]:
# if values are int than use this to make into str and 0:0 for convert to seconds function to work
df.loc[df['top'] == 0, 'top'] = '0:0'
df.loc[df['top_opp'] == 0, 'top_opp'] = '0:0'

In [100]:
# Create the home_results column to show if home teams won or lost 
df['home_results'] = ((df['result'] == 'W') & (df['host'] == 'home')) | ((df['result'] == 'L') & (df['host'] == 'away'))
df['home_results'] = df['home_results'].astype(int)

In [102]:
df.head(3)

,season,team,week,day,date,result,ot,host,opp,pts,...,4dconv_opp,4datt_opp,top_opp,team_full_name,game_id,home_team,away_team,total_top,opp_total_top,home_results
0,2024,CRD,1,Sun,September 8,L,no,away,Buffalo Bills,28.0,...,2.0,2.0,30:30,Arizona Cardinals,2024_1_Arizona Cardinals_Buffalo Bills,Buffalo Bills,Arizona Cardinals,1770,1830,1
1,2024,CRD,2,Sun,September 15,W,no,home,Los Angeles Rams,41.0,...,1.0,3.0,23:06,Arizona Cardinals,2024_2_Arizona Cardinals_Los Angeles Rams,Arizona Cardinals,Los Angeles Rams,2214,1386,1
2,2024,CRD,3,Sun,September 22,L,no,home,Detroit Lions,13.0,...,0.0,1.0,36:49,Arizona Cardinals,2024_3_Arizona Cardinals_Detroit Lions,Arizona Cardinals,Detroit Lions,1391,2209,0

In [109]:
def parse_month_day_with_season(row):
    try:
        # Parse the date string
        date = datetime.strptime(row['date'], "%B %d")
        # Set the year from the 'season' column
        return date.replace(year=row['season'])
    except ValueError:
        return pd.NaT

# Apply the parser to the DataFrame
df['parsed_date'] = df.apply(parse_month_day_with_season, axis=1)

In [110]:
df

,season,team,week,day,date,result,ot,host,opp,pts,...,4datt_opp,top_opp,team_full_name,game_id,home_team,away_team,total_top,opp_total_top,home_results,parsed_date
0,2024,CRD,1,Sun,September 8,L,no,away,Buffalo Bills,28.0,...,2.0,30:30,Arizona Cardinals,2024_1_Arizona Cardinals_Buffalo Bills,Buffalo Bills,Arizona Cardinals,1770,1830,1,2024-09-08
1,2024,CRD,2,Sun,September 15,W,no,home,Los Angeles Rams,41.0,...,3.0,23:06,Arizona Cardinals,2024_2_Arizona Cardinals_Los Angeles Rams,Arizona Cardinals,Los Angeles Rams,2214,1386,1,2024-09-15
2,2024,CRD,3,Sun,September 22,L,no,home,Detroit Lions,13.0,...,1.0,36:49,Arizona Cardinals,2024_3_Arizona Cardinals_Detroit Lions,Arizona Cardinals,Detroit Lions,1391,2209,0,2024-09-22
3,2024,CRD,4,Sun,September 29,L,no,home,Washington Commanders,14.0,...,1.0,33:22,Arizona Cardinals,2024_4_Arizona Cardinals_Washington Commanders,Arizona Cardinals,Washington Commanders,1598,2002,0,2024-09-29
4,2024,CRD,5,Sun,October 6,W,no,away,San Francisco 49ers,24.0,...,1.0,32:58,Arizona Cardinals,2024_5_Arizona Cardinals_San Francisco 49ers,San Francisco 49ers,Arizona Cardinals,1622,1978,0,2024-10-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,2024,SEA,6,Thu,October 10,L,no,home,San Francisco 49ers,24.0,...,0.0,33:03,Seattle Seahawks,2024_6_San Francisco 49ers_Seattle Seahawks,Seattle Seahawks,San Francisco 49ers,1617,1983,0,2024-10-10
268,2024,SEA,11,Sun,November 17,W,no,away,San Francisco 49ers,20.0,...,0.0,33:25,Seattle Seahawks,2024_11_San Francisco 49ers_Seattle Seahawks,San Francisco 49ers,Seattle Seahawks,1595,2005,0,2024-11-17
269,2024,SFO,10,Sun,November 10,W,no,away,Tampa Bay Buccaneers,23.0,...,1.0,28:12,San Francisco 49ers,2024_10_San Francisco 49ers_Tampa Bay Buccaneers,Tampa Bay Buccaneers,San Francisco 49ers,1908,1692,0,2024-11-10
270,2024,TAM,1,Sun,September 8,W,no,home,Washington Commanders,37.0,...,1.0,26:19,Tampa Bay Buccaneers,2024_1_Tampa Bay Buccaneers_Washington Commanders,Tampa Bay Buccaneers,Washington Commanders,2021,1579,1,2024-09-08
271,2024,OTI,13,Sun,December 1,L,no,away,Washington Commanders,19.0,...,1.0,40:13,Tennessee Titans,2024_13_Tennessee Titans_Washington Commanders,Washington Commanders,Tennessee Titans,1187,2413,1,2024-12-01

In [111]:
df['season'] = df['parsed_date'].dt.year
df['day_of_week'] = df['parsed_date'].dt.dayofweek
df['month'] = df['parsed_date'].dt.month

In [113]:
df.rename(columns={'ot':'overtime'}, inplace=True)

In [115]:
df['overtime'] = df['overtime'].apply(lambda x: 1 if x == 'yes' else 0)

In [117]:
df['game_id'] = df.apply(lambda row: f"{row['season']}_{row['week']}_{'_'.join([row['home_team'], row['away_team']])}", axis=1)

In [119]:
pd.options.display.max_columns = None
df.head(3)

,season,team,week,day,date,result,overtime,host,opp,pts,opp_pts,pass_cmp,pass_att,pass_yds,pass_td,int,sk,yds_lost_sks,yds_pass_att,net_yds_pass_att,cmp%,pass_rating,rush_att,rush_yds,rush_yds_att,rush_td,fgm,fga,xpm,xpa,pnt,punt_yds,3dconv,3datt,4dconv,4datt,top,pass_cmp_opp,pass_att_opp,pass_yds_opp,pass_td_opp,int_opp,sk_opp,yds_lost_sks_opp,yds_pass_att_opp,net_yds_pass_att_opp,cmp%_opp,pass_rating_opp,rush_att_opp,rush_yds_opp,rush_yds_att_opp,rush_td_opp,fgm_opp,fga_opp,xpm_opp,xpa_opp,pnt_opp,punt_yds_opp,3dconv_opp,3datt_opp,4dconv_opp,4datt_opp,top_opp,team_full_name,game_id,home_team,away_team,total_top,opp_total_top,home_results,parsed_date,day_of_week,month
0,2024,CRD,1,Sun,September 8,L,0,away,Buffalo Bills,28.0,34.0,21.0,31.0,146.0,1.0,0.0,4.0,16.0,5.2,4.2,67.7,88.9,25.0,124.0,5.0,1.0,2.0,2.0,2.0,2.0,2.0,78.0,7.0,13.0,0.0,1.0,29:30,18.0,23.0,222.0,2.0,0.0,2.0,10.0,10.1,8.9,78.3,135.9,33.0,130.0,3.9,2.0,2.0,2.0,4.0,4.0,2.0,85.0,3.0,9.0,2.0,2.0,30:30,Arizona Cardinals,2024_1_Buffalo Bills_Arizona Cardinals,Buffalo Bills,Arizona Cardinals,1770,1830,1,2024-09-08,6,9
1,2024,CRD,2,Sun,September 15,W,0,home,Los Angeles Rams,41.0,10.0,17.0,21.0,258.0,3.0,0.0,1.0,8.0,12.7,11.7,81.0,157.4,40.0,231.0,5.8,1.0,2.0,2.0,5.0,5.0,1.0,60.0,7.0,11.0,0.0,0.0,36:54,19.0,27.0,192.0,0.0,0.0,5.0,24.0,8.0,6.0,70.4,90.4,20.0,53.0,2.7,1.0,1.0,1.0,1.0,1.0,4.0,215.0,2.0,11.0,1.0,3.0,23:06,Arizona Cardinals,2024_2_Arizona Cardinals_Los Angeles Rams,Arizona Cardinals,Los Angeles Rams,2214,1386,1,2024-09-15,6,9
2,2024,CRD,3,Sun,September 22,L,0,home,Detroit Lions,13.0,20.0,21.0,34.0,200.0,1.0,1.0,1.0,7.0,6.1,5.7,61.8,75.6,18.0,77.0,4.3,0.0,2.0,2.0,1.0,1.0,5.0,260.0,1.0,9.0,0.0,2.0,23:11,18.0,23.0,186.0,2.0,1.0,2.0,13.0,8.7,7.4,78.3,111.2,43.0,187.0,4.3,1.0,0.0,0.0,2.0,3.0,5.0,247.0,6.0,12.0,0.0,1.0,36:49,Arizona Cardinals,2024_3_Arizona Cardinals_Detroit Lions,Arizona Cardinals,Detroit Lions,1391,2209,0,2024-09-22,6,9

In [123]:
# Step 2 & 3: Create and assign statistics for home and away teams
stats_columns = ['pts', 'pass_cmp', 'pass_att', 'pass_yds', 'pass_td', 'int', 'sk',
                 'yds_lost_sks', 'yds_pass_att','net_yds_pass_att', 'cmp%', 'pass_rating', 'rush_att',
                 'rush_yds','rush_yds_att', 'rush_td', 'fgm', 'fga', 'xpm', 'xpa', 'pnt','punt_yds', '3dconv',
                 '3datt', '4dconv', '4datt', 'total_top']
opp_stats_columns = ['opp_pts','pass_cmp_opp', 'pass_att_opp', 'pass_yds_opp', 'pass_td_opp','int_opp', 'sk_opp',
                     'yds_lost_sks_opp', 'yds_pass_att_opp','net_yds_pass_att_opp', 'cmp%_opp', 'pass_rating_opp',
                     'rush_att_opp','rush_yds_opp', 'rush_yds_att_opp', 'rush_td_opp', 'fgm_opp', 'fga_opp',
                     'xpm_opp', 'xpa_opp', 'pnt_opp', 'punt_yds_opp', '3dconv_opp','3datt_opp', '4dconv_opp',
                     '4datt_opp', 'opp_total_top']

In [125]:
df['home_is_team'] = df['home_team'] == df['team_full_name']

In [127]:
for team_stat, opp_stat in zip(stats_columns, opp_stats_columns):
    df[f'home_{team_stat}'] = df.apply(lambda row: row[team_stat] if row['home_is_team'] else row[opp_stat], axis=1)
    df[f'away_{team_stat}'] = df.apply(lambda row: row[opp_stat] if row['home_is_team'] else row[team_stat], axis=1)

In [139]:
df.head(1)

,season,team,week,day,date,result,overtime,host,opp,top,top_opp,game_id,home_team,away_team,home_results,date,day_of_week,month,home_pts,away_pts,home_pass_cmp,away_pass_cmp,home_pass_att,away_pass_att,home_pass_yds,away_pass_yds,home_pass_td,away_pass_td,home_int,away_int,home_sk,away_sk,home_yds_lost_sks,away_yds_lost_sks,home_yds_pass_att,away_yds_pass_att,home_net_yds_pass_att,away_net_yds_pass_att,home_cmp%,away_cmp%,home_pass_rating,away_pass_rating,home_rush_att,away_rush_att,home_rush_yds,away_rush_yds,home_rush_yds_att,away_rush_yds_att,home_rush_td,away_rush_td,home_fgm,away_fgm,home_fga,away_fga,home_xpm,away_xpm,home_xpa,away_xpa,home_pnt,away_pnt,home_punt_yds,away_punt_yds,home_3dconv,away_3dconv,home_3datt,away_3datt,home_4dconv,away_4dconv,home_4datt,away_4datt,home_top,away_top
0,2024,CRD,1,Sun,September 8,L,0,away,Buffalo Bills,29:30,30:30,2024_1_Buffalo Bills_Arizona Cardinals,Buffalo Bills,Arizona Cardinals,1,2024-09-08,6,9,34.0,28.0,18.0,21.0,23.0,31.0,222.0,146.0,2.0,1.0,0.0,0.0,2.0,4.0,10.0,16.0,10.1,5.2,8.9,4.2,78.3,67.7,135.9,88.9,33.0,25.0,130.0,124.0,3.9,5.0,2.0,1.0,2.0,2.0,2.0,2.0,4.0,2.0,4.0,2.0,2.0,2.0,85.0,78.0,3.0,7.0,9.0,13.0,2.0,0.0,2.0,1.0,1830,1770

In [137]:
old_data.head(1)

,game_id,home_team,away_team,date,season,month,week,day_of_week,overtime,home_pts,away_pts,home_pass_cmp,away_pass_cmp,home_pass_att,away_pass_att,home_pass_yds,away_pass_yds,home_pass_td,away_pass_td,home_int,away_int,home_sk,away_sk,home_yds_lost_sks,away_yds_lost_sks,home_yds_pass_att,away_yds_pass_att,home_net_yds_pass_att,away_net_yds_pass_att,home_cmp%,away_cmp%,home_pass_rating,away_pass_rating,home_rush_att,away_rush_att,home_rush_yds,away_rush_yds,home_rush_yds_att,away_rush_yds_att,home_rush_td,away_rush_td,home_fgm,away_fgm,home_fga,away_fga,home_xpm,away_xpm,home_xpa,away_xpa,home_pnt,away_pnt,home_punt_yds,away_punt_yds,home_3dconv,away_3dconv,home_3datt,away_3datt,home_4dconv,away_4dconv,home_4datt,away_4datt,home_top,away_top,pts_diff_home,pass_yds_diff_home,rush_yds_diff_home,top_diff_home,home_total_yds,away_total_yds,home_results
0,2000_1_New York Giants_Arizona Cardinals,New York Giants,Arizona Cardinals,2000-09-03,2000,9,1,6,0,21,16,17,28,25,49,172,312,0,2,1,3,0,1,0,6,6.9,6.5,6.9,6.2,68.0,57.1,70.7,64.3,41,20,223,43,5.4,2.2,3,0,0,1,0,1,3,1,3,1,6,5,155,210,7,6,14,15,0,0,0,2,1890,1710,5,-140,180,180,395,355,1

In [135]:
df = df.drop(columns=stats_columns + opp_stats_columns + ['date','team_full_name','home_is_team','team','day',
                                                          'result','host','opp','top','top_opp'])

In [138]:
df.rename(columns = {'parsed_date': 'date','ot':'overtime','home_total_top': 'home_top',
                     'away_total_top': 'away_top'},inplace = True)

In [168]:
# Get the common columns in the order they appear in old_data
common_columns = [col for col in old_data.columns if col in df.columns]

# Get the additional columns in df that are not in old_data
additional_columns = [col for col in df.columns if col not in old_data.columns]

# Reorder df columns
dff = df[common_columns + additional_columns]
# df = df[common_columns]

In [ ]:
# this is the right code to rename columns, above line was to edit this specific df
df.rename(columns = {'parsed_date': 'date', 'ot':'overtime','home_total_top': 'home_top',
                     'away_total_top': 'away_top'},inplace = True)

In [175]:
len(common_columns), len(additional_columns)

(64, 7)

In [181]:
not_sharedd

['top_diff_home',
 'pass_yds_diff_home',
 'pts_diff_home',
 'away_total_yds',
 'home_total_yds',
 'rush_yds_diff_home']

In [182]:
# Point difference
dff['pts_diff_home'] = dff['home_pts'] - dff['away_pts']

# Passing yards difference
dff['pass_yds_diff_home'] = dff['home_pass_yds'] - dff['away_pass_yds']

# Rushing yards difference
dff['rush_yds_diff_home'] = dff['home_rush_yds'] - dff['away_rush_yds']

# Time of possession difference
dff['top_diff_home'] = dff['home_top'] - dff['away_top']

#Total yards by home team
dff['home_total_yds']= dff['home_pass_yds'] + dff['home_rush_yds']

# Total yards by away team
dff['away_total_yds']= dff['away_pass_yds'] + dff['away_rush_yds']

In [184]:
dff.head(2)

,game_id,home_team,away_team,date,date,season,month,week,day_of_week,overtime,home_pts,away_pts,home_pass_cmp,away_pass_cmp,home_pass_att,away_pass_att,home_pass_yds,away_pass_yds,home_pass_td,away_pass_td,home_int,away_int,home_sk,away_sk,home_yds_lost_sks,away_yds_lost_sks,home_yds_pass_att,away_yds_pass_att,home_net_yds_pass_att,away_net_yds_pass_att,home_cmp%,away_cmp%,home_pass_rating,away_pass_rating,home_rush_att,away_rush_att,home_rush_yds,away_rush_yds,home_rush_yds_att,away_rush_yds_att,home_rush_td,away_rush_td,home_fgm,away_fgm,home_fga,away_fga,home_xpm,away_xpm,home_xpa,away_xpa,home_pnt,away_pnt,home_punt_yds,away_punt_yds,home_3dconv,away_3dconv,home_3datt,away_3datt,home_4dconv,away_4dconv,home_4datt,away_4datt,home_top,away_top,home_results,team,day,result,host,opp,top,top_opp,pts_diff_home,pass_yds_diff_home,rush_yds_diff_home,top_diff_home,home_total_yds,away_total_yds
0,2024_1_Buffalo Bills_Arizona Cardinals,Buffalo Bills,Arizona Cardinals,September 8,2024-09-08,2024,9,1,6,0,34.0,28.0,18.0,21.0,23.0,31.0,222.0,146.0,2.0,1.0,0.0,0.0,2.0,4.0,10.0,16.0,10.1,5.2,8.9,4.2,78.3,67.7,135.9,88.9,33.0,25.0,130.0,124.0,3.9,5.0,2.0,1.0,2.0,2.0,2.0,2.0,4.0,2.0,4.0,2.0,2.0,2.0,85.0,78.0,3.0,7.0,9.0,13.0,2.0,0.0,2.0,1.0,1830,1770,1,CRD,Sun,L,away,Buffalo Bills,29:30,30:30,6.0,76.0,6.0,60,352.0,270.0
1,2024_2_Arizona Cardinals_Los Angeles Rams,Arizona Cardinals,Los Angeles Rams,September 15,2024-09-15,2024,9,2,6,0,41.0,10.0,17.0,19.0,21.0,27.0,258.0,192.0,3.0,0.0,0.0,0.0,1.0,5.0,8.0,24.0,12.7,8.0,11.7,6.0,81.0,70.4,157.4,90.4,40.0,20.0,231.0,53.0,5.8,2.7,1.0,1.0,2.0,1.0,2.0,1.0,5.0,1.0,5.0,1.0,1.0,4.0,60.0,215.0,7.0,2.0,11.0,11.0,0.0,1.0,0.0,3.0,2214,1386,1,CRD,Sun,W,home,Los Angeles Rams,36:54,23:06,31.0,66.0,178.0,828,489.0,245.0

In [199]:
#wont be necessary to include this line, as in function it should have been removed before 
dff = dff.drop(dff.columns[3], axis=1)

In [202]:
jan_games = dff['month'] == 1
dff.loc[jan_games, 'date'] = dff.loc[jan_games, 'date'] + pd.DateOffset(years=1)

KeyError: 'date'

In [ ]:
# next step is to sort the data
# df = df.sort_values(by='date', ascending=True,ignore_index=True)

# pd.read_csv('getting_there.csv', parse_dates=['date'], date_format='%Y-%m-%d')

In [178]:
old_data.shape[1] 
#df.shape[1]

70

In [ ]:
def final_cleaned_df(df):#, filename):

    #if filename is None:
    #    filename = str(input('Enter a filename for this data to save as a csv file (no need to add extenison of file): ')).strip() + '.csv'
    
    team_code_map = {
    'CRD': 'Arizona Cardinals',
    'ATL': 'Atlanta Falcons',
    'RAV': 'Baltimore Ravens',
    'BUF': 'Buffalo Bills',
    'CAR': 'Carolina Panthers',
    'CHI': 'Chicago Bears',
    'CIN': 'Cincinnati Bengals',
    'CLE': 'Cleveland Browns',
    'DAL': 'Dallas Cowboys',
    'DEN': 'Denver Broncos',
    'DET': 'Detroit Lions',
    'GNB': 'Green Bay Packers',
    'CLT': 'Indianapolis Colts',
    'JAX': 'Jacksonville Jaguars',
    'KAN': 'Kansas City Chiefs',
    'SDG': 'Los Angeles Chargers',
    'RAM': 'Los Angeles Rams',
    'RAI': 'Las Vegas Raiders',
    'MIA': 'Miami Dolphins',
    'MIN': 'Minnesota Vikings',
    'NWE': 'New England Patriots',
    'NOR': 'New Orleans Saints',
    'NYG': 'New York Giants',
    'NYJ': 'New York Jets',
    'PHI': 'Philadelphia Eagles',
    'PIT': 'Pittsburgh Steelers',
    'SEA': 'Seattle Seahawks',
    'SFO': 'San Francisco 49ers',
    'TAM': 'Tampa Bay Buccaneers',
    'OTI': 'Tennessee Titans',
    'WAS': 'Washington Commanders',
    'HTX': 'Houston Texans'
    }

    # Step 1: Replace team abbreviations in the 'team' column with full names
    df['team_full_name'] = df['team'].map(team_code_map)

    #Create a unique identifier for each game
    # This ensures each game is represented only once, even if it's recorded from both teams' perspectives
    df['game_id'] = df.apply(lambda row: f"{row['season']}_{row['week']}_{'_'.join(sorted([row['team_full_name'], row['opp']]))}", axis=1)

    # Step 2: Drop duplicate entries based on the game_id
    # Keep only one entry for each game (e.g., keeping the first occurrence)
    df = df.drop_duplicates(subset='game_id', ignore_index= True)
    
    
    # Step 3: Drop the 'game_id' column if it's no longer needed
    #df_cleaned = df_cleaned.drop(columns=['game_id'])    


    # Made home and away columns 
    df['home_team'] = df.apply(lambda row: row['team_full_name'] if row['host'] == 'home' else row['opp'], axis = 1)
    df['away_team'] = df.apply(lambda row: row['opp'] if row['host'] == 'home' else row['team_full_name'], axis = 1)

    # Since we are dealing with future data that data does not exist yet to be able to predict on 
    df.fillna('0', inplace=True)
    
    # values shoule be a string and make it into '0:0' to be able to convert to seconds 
    df.loc[df['top'] == '0', 'top'] = '0:0'
    df.loc[df['top_opp'] == '0', 'top_opp'] = '0:0'
    
    # Apply the function to the 'top' column
    df['total_top'] = df['top'].apply(convert_to_seconds)
    df['opp_total_top'] = df['top_opp'].apply(convert_to_seconds)

    # Create the home_results column to show if home teams won or lost 
    df['home_results'] = ((df['result'] == 'W') & (df['host'] == 'home')) | ((df['result'] == 'L') & (df['host'] == 'away'))
    df['home_results'] = df['home_results'].astype(int)

    # Apply the parser to the DataFrame
    df['parsed_date'] = df.apply(parse_month_day_with_season, axis=1)

    # making columns for season, day of week, and month
    df['season'] = df['parsed_date'].dt.year
    df['day_of_week'] = df['parsed_date'].dt.dayofweek
    df['month'] = df['parsed_date'].dt.month

    # column encoded for overtime 
    df['ot'] = df['ot'].apply(lambda x: 1 if x == 'yes' else 0)

    # game id is redone but look at optimizing later
    df['game_id'] = df.apply(lambda row: f"{row['season']}_{row['week']}_{'_'.join([row['home_team'], row['away_team']])}", axis=1)


    # Step 2 & 3: Create and assign statistics for home and away teams
    stats_columns = ['pts', 'pass_cmp', 'pass_att', 'pass_yds', 'pass_td', 'int', 'sk',
                     'yds_lost_sks', 'yds_pass_att','net_yds_pass_att', 'cmp%', 'pass_rating', 'rush_att',
                     'rush_yds','rush_yds_att', 'rush_td', 'fgm', 'fga', 'xpm', 'xpa', 'pnt','punt_yds', '3dconv',
                     '3datt', '4dconv', '4datt', 'total_top']
    opp_stats_columns = ['opp_pts','pass_cmp_opp', 'pass_att_opp', 'pass_yds_opp', 'pass_td_opp','int_opp', 'sk_opp',
                         'yds_lost_sks_opp', 'yds_pass_att_opp','net_yds_pass_att_opp', 'cmp%_opp', 'pass_rating_opp',
                         'rush_att_opp','rush_yds_opp', 'rush_yds_att_opp', 'rush_td_opp', 'fgm_opp', 'fga_opp',
                         'xpm_opp', 'xpa_opp', 'pnt_opp', 'punt_yds_opp', '3dconv_opp','3datt_opp', '4dconv_opp',
                         '4datt_opp', 'opp_total_top']

    # line is needed to make sure the stats go to the correct team
    df['home_is_team'] = df['home_team'] == df['team_full_name']

    # assigning stats to home and away team 
    for team_stat, opp_stat in zip(stats_columns, opp_stats_columns):
        df[f'home_{team_stat}'] = df.apply(lambda row: row[team_stat] if row['home_is_team'] else row[opp_stat], axis=1)
        df[f'away_{team_stat}'] = df.apply(lambda row: row[opp_stat] if row['home_is_team'] else row[team_stat], axis=1)

    # columns to drop
    df = df.drop(columns=stats_columns + opp_stats_columns + ['date','team_full_name','home_is_team','team','day',
                                                          'result','host','opp','top','top_opp'])

    # rename columns 
    df.rename(columns = {'parsed_date': 'date', 'ot':'overtime','home_total_top': 'home_top',
                         'away_total_top': 'away_top'},inplace = True)

    # Point difference
    df['pts_diff_home'] = df['home_pts'] - df['away_pts']
    
    # Passing yards difference
    df['pass_yds_diff_home'] = df['home_pass_yds'] - df['away_pass_yds']
    
    # Rushing yards difference
    df['rush_yds_diff_home'] = df['home_rush_yds'] - df['away_rush_yds']
    
    # Time of possession difference
    df['top_diff_home'] = df['home_top'] - df['away_top']
    
    #Total yards by home team
    df['home_total_yds']= df['home_pass_yds'] + df['home_rush_yds']
    
    # Total yards by away team
    df['away_total_yds']= df['away_pass_yds'] + df['away_rush_yds']

    old_data = pd.read_csv('getting_there.csv')
    
    # Get the common columns in the order they appear in old_data
    common_columns = [col for col in old_data.columns if col in df.columns]

    # Get the additional columns in df that are not in old_data
    # need old_data df to compare to be able to run this code 
    additional_columns = [col for col in df.columns if col not in old_data.columns]

    # Reorder df columns
    df = df[common_columns + additional_columns]
    
    # edit the year on jan games that should be + 1 year i.e. 2024 should be jan 3, 2025, then reset index
    jan_games = df['month'] == 1
    df.loc[jan_games, 'date'] = df.loc[jan_games, 'date'] + pd.DateOffset(years=1)
    df.reset_index(drop= 'index',inplace=True)
    
    # sort the data by the date
    df = df.sort_values(by='date', ascending=True, ignore_index=True)

    #df.to_csv(filename, index = False)
    
    return df
    
    #pd.read_csv(filename, parse_dates=['date'], date_format='%Y-%m-%d')

In [ ]:
# Function to convert "minutes:seconds" to total seconds
def convert_to_seconds(time_str):
    minutes, seconds = map(int, time_str.split(':'))
    return minutes * 60 + seconds

# Function to convert the date column to datetime and parser date information 
def parse_month_day_with_season(row):
    try:
        # Parse the date string
        date = datetime.strptime(row['date'], "%B %d")
        # Set the year from the 'season' column
        return date.replace(year=row['season'])
    except ValueError:
        return pd.NaT

In [ ]:
# need to go over final_cleaned function to make sure it works -- done
# add all functions to a .py file -- done
# run entire functions to see if it works -- done